In [1]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할 떄 사용하는 자료구조
# 0차원 텐서: 스칼라 25 - 단일 데이터
# 1차원 텐서(벡터): 스칼라들의 집합- 리스트 형태 [1,2,3,4]
# 2차원 텐서(행렬): 행과 열로 이루어진 데이터, 표데이터 , 흑백이미지(가로픽셀X세로픽셀)
# 3차원 텐서 : 컬러이미지, 흑백이미지+ 채널정보(RGB)
# 고차원 텐서: 동영상 : 가로픽셀 X 세로픽셀 x 채널정보 x 이미지갯수

#데이터였던 표준 형식을 취함: 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병열연산에 유리
# 딥러닝 프레임워크 : 텐서플로, 파이토치

In [2]:
#기본 연산
import torch
# 빈 텐서 생성
x = torch.empty(3,4) # numpy array와 비슷
x

c:\Users\Playdata2\miniconda3\envs\deep\lib\site-packages\torch\_subclasses\functional_tensor.py:279: UserWarning: Failed to initialize NumPy: DLL load failed while importing _multiarray_umath: 지정된 모듈을 찾을 수 없습니다. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


tensor([[-9.2261e-41,  1.3929e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
# 랜덤 텐서
x= torch.rand(3,4)
x

In [3]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [4]:
# 1로 채워진 텐서
torch.ones(3,4,dtype=torch.long)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [5]:
import numpy as np
print(np.array([3.5,3,2.1]))
print(torch.tensor([3.5,3,2.1]))

[3.5 3.  2.1]
tensor([3.5000, 3.0000, 2.1000])


In [6]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x,dtype=torch.float) # 똑같이 복사
x,y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 1.3950,  0.1035, -0.0579,  0.0871],
         [ 1.3337, -0.9343,  0.5064,  0.6121],
         [ 0.2740,  0.9723, -2.3242,  1.5297]]))

In [7]:
import torch 
x = torch.rand(3,4)
y = torch.rand(3,4)
x, y
x+y

tensor([[1.3922, 1.5046, 0.4105, 1.6748],
        [1.4184, 0.0743, 1.0077, 1.1316],
        [1.0105, 1.3054, 0.7043, 1.1240]])

In [8]:
torch.add(x,y)


tensor([[1.3922, 1.5046, 0.4105, 1.6748],
        [1.4184, 0.0743, 1.0077, 1.1316],
        [1.0105, 1.3054, 0.7043, 1.1240]])

In [9]:
# im-place   y= y+x y+= x
y.add_(x)

tensor([[1.3922, 1.5046, 0.4105, 1.6748],
        [1.4184, 0.0743, 1.0077, 1.1316],
        [1.0105, 1.3054, 0.7043, 1.1240]])

In [10]:
y

tensor([[1.3922, 1.5046, 0.4105, 1.6748],
        [1.4184, 0.0743, 1.0077, 1.1316],
        [1.0105, 1.3054, 0.7043, 1.1240]])

In [11]:
# 행렬 곱셈
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y),x@y #파이썬 3.5 부터 x@y

(tensor([[0.7047, 0.0339, 0.5557, 0.0943],
         [0.4366, 0.7937, 0.2033, 0.0793],
         [0.5671, 0.7021, 0.4198, 0.3035]]),
 tensor([[0.3342, 0.1216, 0.3987, 0.4465, 0.2730],
         [0.9541, 0.2442, 0.9421, 0.1171, 0.1311],
         [0.3581, 0.1256, 0.0661, 0.4539, 0.0458],
         [0.3042, 0.5353, 0.3640, 0.0802, 0.3253]]),
 tensor([[0.4955, 0.2142, 0.3840, 0.5784, 0.2530],
         [1.0002, 0.3149, 0.9642, 0.3865, 0.2584],
         [1.1021, 0.4556, 1.0259, 0.5503, 0.3648]]),
 tensor([[0.4955, 0.2142, 0.3840, 0.5784, 0.2530],
         [1.0002, 0.3149, 0.9642, 0.3865, 0.2584],
         [1.1021, 0.4556, 1.0259, 0.5503, 0.3648]]))

In [12]:
# 행렬 곱셈 하려면 3 X2 2X4 가운데 열이 같아야함 3X4행렬이 나옴

In [13]:
# 슬라이싱 가능
x = torch.rand(4,5)
x[1,1], x[1,1].item(),x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item() )
 

(tensor(0.0588),
 0.058823585510253906,
 tensor(0.0588),
 0.058823585510253906,
 torch.Tensor,
 float)

In [14]:
type(x[1,1]), type(x[1,1].item())
# 이거 차이로 에러가 날 수 있어서 중요한 역할

(torch.Tensor, float)

In [15]:
# 텐서 크기 변경  reshape, view             numpy 동일한 기능 reshape
x = torch.rand(4,4)
y = x.view(16)
y  = x.view(-1) # -1 자동계산
x, y, x.shape, y.shape

(tensor([[0.2623, 0.4619, 0.1238, 0.5872],
         [0.2506, 0.6735, 0.3456, 0.4082],
         [0.0707, 0.7956, 0.4615, 0.8851],
         [0.6350, 0.2825, 0.1537, 0.6870]]),
 tensor([0.2623, 0.4619, 0.1238, 0.5872, 0.2506, 0.6735, 0.3456, 0.4082, 0.0707,
         0.7956, 0.4615, 0.8851, 0.6350, 0.2825, 0.1537, 0.6870]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [16]:
# x =  4by 4
# view : reshape #텐서 모양 변경
# size: reshape #텐서 모양 확인
# 가독성.... view size 사용되었다는 것은 해당 자료구조가 텐서라는것을 명시
x.view(-1,8), x.size()
#x.view(-1,-1) 오류남 오직 1개만 추론, 예측할 수 있고 고정할 수 있어서 

(tensor([[0.2623, 0.4619, 0.1238, 0.5872, 0.2506, 0.6735, 0.3456, 0.4082],
         [0.0707, 0.7956, 0.4615, 0.8851, 0.6350, 0.2825, 0.1537, 0.6870]]),
 torch.Size([4, 4]))

In [20]:
%conda install numpy

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [23]:
%pip install -U pip setuptools wheel
%pip install --force-reinstall --no-cache-dir numpy


Note: you may need to restart the kernel to use updated packages.
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 12.9/12.9 MB 116.0 MB/s  0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.


In [21]:
%pip show numpy


Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
         All rights reserved.
         
         Redistribution and use in source and binary forms, with or without
         modification, are permitted provided that the following conditions are
         met:
         
             * Redistributions of source code must retain the above copyright
                notice, this list of conditions and the following disclaimer.
         
             * Redistributions in binary form must reproduce the above
                copyright notice, this list of conditions and the following
                disclaimer in the documentation and/or other materials provided
                with the distribution.
         
             * Neither the name of the NumPy Developers nor the names of any
                contributors may be used to 

In [24]:
#텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
a.numpy() #텐서 자체를 넘파이하기

RuntimeError: Numpy is not available

In [ ]:
#넘파이-> 텐서
import torch
import numpy as np
a = np.array([1,2,3,4,5])
torch.from_numpy(a)

In [ ]:
# GPU 사용
if torch.cuda.is_available():
    device = torch.device('cuda') # gpu
    #텐서들은 gpu에서 연산해야되기 떄문에 생성을 gpu에서 생성
    x = torch.ones(5,device=device) #gpu  생성
    y = torch.ones(5) #cpu
    y = y.to(device) #cpu->gpu로 이동
    z = x+y
    print(f'GPU 연산결과 : {z}')
    print(f'다시 CPU로 :{z.to("cpu",torch.double)}')
else:
    print('CUDA를 사용할 수 없습니다')
    device = torch.device('cpu')

In [ ]:
torch.cuda.is_available()

In [ ]:
#행렬의 곱
# (x, y) * (x1,y1)
# y , x1의 차수는 같아야한다...
# 행렬곱의 결과는 x, y1

#텐서는 딥러닝을 위해 만들 자료구조... 내부에 gpu연산에 특화된 구조 일반적인 모양은 넘파이와 동일
#텐서는 gpu연산을 지원ZZ

In [ ]:
#자동 미분(Autograd) 매 계산과정마다 해당 계산과정의 미분값을 저장
#파이토치 required_grad  = True로 설정하면 계산그래프라는 형태로 기록 -  동영상 녹화와 비슷한 원리
# .backward() 호출하면 이과중을 거꾸로 되감으면서 각단계의 미분값을 계산해 최종 기울기를 얻는다

In [ ]:
x = torch.ones(2,2,requires_grad=True)
x, x.size()

In [ ]:
y = x+2 #y도 계산 그래프에 추가
print(y, y.grad_fn)
z= y*y*3
out = z.mean()
z, out

In [ ]:
# 기울기... 구하는 과정을... 역전파----> 기울기 계산
# 최종결과가 out에서부터 시작해서 계산그래프를 거꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 x에 대해서 미분
out.backward()
x.grad


In [ ]:
# out=1/4(z1+z2+z3+z4)
# x=3y^2
# y = x+2

#d-out/dxi = 


In [ ]:
#기울기 제어
#역전파, torch.no_grad, detach
# required_grad = True 연상 추적
import torch 
torch.randn(3, requires_grad=True)
print(x)
# y는 x로부터 연산기록을 물려받음
y = x * 2
#노름(유클리드 노름) 벡터의 크기를 측정하는 방법(원점으로 부터 벡터까지의 거리) 모든 요소를 각각 제곱하고 모두 더해서 결과에 제곱근(루트)
#y의 실제데이터의 크기를 확인해서 반복
i = 0
while y.data.norm() < 1000:
    y = y*2
    i +=1
print(f'y:{y}')
print(f'반복횟수 :{i} y=x*2^i+1')
y.data.norm() 

#벡터에 대한 역전파(야코비안 행렬)
#벡터를 벡터로 미분하면 결과 행렬인 야코비안 행렬
#pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 야코비안- 벡터 곱을 계산해서 메모리를 절약
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v) #y를 x에 대해 미분한 야콥미안 행렬과 입력으로 제공된 벡터 v를 곱하라는 의미
# Vt * J
print(f'x.grad: {x.grad}')

```
스칼라 백워드 Scalar Backward : 역전파로 구하는 기울기가 하나일 때
out.backward()
최종점수가 숫자하나, ex)수학공부 1시간했을 때 최종점수에 몇점의 영향을 줬는지
최종목표가 하나(스칼라) 이기 때문에 각 원인(각 변수)의 기여도를 바로 계산

벡터 백워드 Vector Backward: 기울기가 여러개 일때 
y.backward()
과목별 점수가 담긴 성적표(벡터) 공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매함 국어성적?  영어성적?
가중치 또는 중요도를 알려주는 벡터 v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인
```

In [ ]:
#각 학습을 진행하면서 도중에 모델의 성능을 평가가 필요- 기울기 계산을 하면 안됨
with torch.no_grad():
    print(f'no grad 내부: {(x**2).requires_grad}')

# .detach() 계산그래프에서 텐서를 분리
print(f'detach 전 {y.requires_grad}')
y = x.detach()
print(f'detach 후 {y.requires_grad}')